// <auto-generated />
namespace PostModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test311 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test311));
        
        string IMigrationMetadata.Id
        {
            get { return "201702072347016_test311"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
